server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Route pour l'authentification (PUBLIC - pas de filtre)
        - id: auth-route
          uri: lb://front-api
          predicates:
            - Path=/auth/**

        # Route pour front-api (PROTÉGÉE)
        - id: front-api
          uri: lb://front-api
          predicates:
            - Path=/full-orders/**
          filters:
            - AuthenticationFilter

        # Route pour order-service (PROTÉGÉE)
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        # Route pour product-service (PROTÉGÉE)
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
