server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
