server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/

spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

mes-config-ms:
  commandes-last: 30
